name: Nightly

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'releases/**'
    tags:
      - 'v**'
  release:
    types: [created]

jobs:
  devops:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: DevOps container image build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build containers
      - name: Build containers
        run: bash devops/build.sh

      # Log into container registries
      - name: Log into Docker Hub
        run: echo "${{ secrets.WBIA_WILDMEBOT_DOCKER_HUB_TOKEN }}" | docker login -u wildmebot --password-stdin
      
      - name: Log into GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      # Push containers out to container registries
      - name: Push to GitHub Packages
        run: bash devops/publish.sh -t nightly -r docker.pkg.github.com
      
